name              "setupvenv"
maintainer        "Caleb Groom"
maintainer_email  "caleb@calebgroom.com"
license           "Apache 2.0"
description       "Cookbook that creates a Python virtual environment and activates it on user login"
version           "0.0.1"
depends           "python"
